---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: disk-usage-monitor

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-disk-usage-monitor
commonLabels:
  app: disk-usage-monitor

resources:
- resources/configmaps.yaml
- resources/cronjobs.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
patches:
