apiVersion: batch/v1
kind: CronJob
metadata:
  name: disk-usage-monitor
  namespace: disk-usage-monitor
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  timeZone: America/Detroit
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-hass
              command:
                - /bin/sh
                - /opt/update_hass.sh
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: hass-token
                      key: TOKEN
                - name: TZ
                  value: America/Detroit
              image: ghcr.io/charlesthomas/disk-usage-monitor:latest
              imagePullPolicy: IfNotPresent
              resources: {}
              volumeMounts:
                - mountPath: /opt
                  name: scripts
                - mountPath: /ssh
                  name: ssh
          restartPolicy: Never
          volumes:
            - name: scripts
              configMap:
                name: scripts
            - name: ssh
              secret:
                secretName: ssh
