---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hass-token
  namespace: disk-usage-monitor
spec:
  target:
    name: hass-token
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        TOKEN: |-
          {{ .hass_token }}
  data:
    - secretKey: hass_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 143c5f7d-5bdd-4006-8ae7-bc715ab72a01
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh
  namespace: disk-usage-monitor
spec:
  target:
    name: ssh
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config: |-
          {{ .config }}
        known_hosts: |-
          {{ .hosts }}
        nas01.id_rsa: |-
          {{ .nas01_key }}
        offsite-backups.id_ed25519: |-
          {{ .offsite_backups_key }}
        seedbox.id_rsa: |-
          {{ .seedbox_key }}
  data:
    - secretKey: config
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: disk-usage-monitor-ssh-config
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
    - secretKey: hosts
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nas02-known-hosts
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
    - secretKey: nas01_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nas01.id_rsa
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
    - secretKey: offsite_backups_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nas02-id_rsa
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
    - secretKey: seedbox_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: seedbox-id_rsa
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore

