---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: offsite-backups
spec:
  target:
    name: tailscale-auth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        TS_AUTHKEY: |-
          {{ .tskey }}
  data:
    - secretKey: tskey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 0d01c153-f8f5-4012-8dbe-4b975be588a1
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
